name: Deploy NextMeal Server

on:
  push:
    branches:
      - main  # Trigger pipeline on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # Step 3: Build, tag, and push Docker image
      - name: Build, tag, and push Docker image
        env:
          ECR_REGISTRY: 529088288756.dkr.ecr.us-west-1.amazonaws.com
          ECR_REPOSITORY: nextmeal-server
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG}

      # Step 4: Deploy to Amazon ECS Service
      - name: Deploy to ECS Service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: nextmeal-service-cluster
          service: nextmeal-auth
          task-definition: nextmeal-task:1
          container-name: nextmeal-container
          image: 529088288756.dkr.ecr.us-west-1.amazonaws.com/nextmeal-server:${{ github.sha }}
          wait-for-service-stability: true
